In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("nba_games.csv",index_col=0)

In [3]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,Team_opp,Total_opp,Home_opp,season,date,won
0,240.0,240.0,38.0,72.0,0.528,16.0,37.0,0.432,18.0,21.0,...,26.2,26.8,155.0,123.0,MIA,107,1,2023,2022-11-07,True
1,240.0,240.0,40.0,84.0,0.476,14.0,39.0,0.359,13.0,15.0,...,41.0,37.3,160.0,121.0,POR,110,0,2023,2022-11-07,False
2,240.0,240.0,41.0,78.0,0.526,8.0,24.0,0.333,15.0,19.0,...,28.6,41.1,250.0,125.0,DAL,90,1,2023,2022-12-14,True
3,240.0,240.0,29.0,74.0,0.392,13.0,38.0,0.342,19.0,26.0,...,12.6,33.0,183.0,110.0,CLE,105,0,2023,2022-12-14,False
4,240.0,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,18.0,...,22.8,29.0,178.0,111.0,DAL,95,1,2016,2015-12-09,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17529,240.0,240.0,43.0,100.0,0.430,9.0,29.0,0.310,18.0,24.0,...,20.0,30.2,147.0,117.0,MIN,106,0,2019,2019-03-21,True
17530,240.0,240.0,41.0,86.0,0.477,16.0,43.0,0.372,15.0,17.0,...,25.0,54.6,253.0,126.0,CHI,130,1,2024,2023-11-06,False
17531,240.0,240.0,48.0,93.0,0.516,18.0,34.0,0.529,16.0,19.0,...,66.7,31.4,200.0,140.0,UTA,113,0,2024,2023-11-06,True
17532,240.0,240.0,33.0,93.0,0.355,12.0,39.0,0.308,19.0,23.0,...,100.0,28.8,230.0,107.0,GSW,112,1,2022,2022-03-08,False
17533,240.0,240.0,44.0,92.0,0.478,13.0,34.0,0.382,11.0,13.0,...,34.0,29.5,189.0,119.0,LAC,97,0,2022,2022-03-08,True

In [4]:
df = df.sort_values("date")

In [5]:
df = df.reset_index(drop=True)

In [6]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,Team_opp,Total_opp,Home_opp,season,date,won
0,240.0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
1,240.0,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,...,57.1,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True
2,240.0,240.0,29.0,82.0,0.354,2.0,16.0,0.125,16.0,22.0,...,100.0,28.0,149.0,89.0,CLE,106,0,2016,2015-10-28,False
3,240.0,240.0,37.0,100.0,0.370,5.0,26.0,0.192,8.0,12.0,...,23.3,29.7,121.0,99.0,WAS,88,0,2016,2015-10-28,False
4,240.0,240.0,33.0,84.0,0.393,7.0,28.0,0.250,15.0,25.0,...,30.8,25.2,134.0,98.0,ORL,87,1,2016,2015-10-28,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17529,240.0,240.0,38.0,82.0,0.463,17.0,46.0,0.370,13.0,14.0,...,50.0,40.0,205.0,124.0,DAL,99,1,2024,2024-06-12,True
17530,240.0,240.0,46.0,91.0,0.505,15.0,37.0,0.405,15.0,22.0,...,50.0,35.9,200.0,138.0,BOS,84,0,2024,2024-06-14,True
17531,240.0,240.0,29.0,80.0,0.363,14.0,41.0,0.341,12.0,13.0,...,100.0,40.8,212.0,99.0,DAL,122,1,2024,2024-06-14,False
17532,240.0,240.0,38.0,89.0,0.427,13.0,39.0,0.333,17.0,20.0,...,36.4,54.6,194.0,133.0,DAL,88,0,2024,2024-06-17,True
17533,240.0,240.0,35.0,78.0,0.449,11.0,37.0,0.297,7.0,13.0,...,15.5,32.3,300.0,110.0,BOS,106,1,2024,2024-06-17,False

In [7]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [8]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,Team_opp,Total_opp,Home_opp,season,date,won
0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
1,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,0.769,...,57.1,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True
2,240.0,29.0,82.0,0.354,2.0,16.0,0.125,16.0,22.0,0.727,...,100.0,28.0,149.0,89.0,CLE,106,0,2016,2015-10-28,False
3,240.0,37.0,100.0,0.370,5.0,26.0,0.192,8.0,12.0,0.667,...,23.3,29.7,121.0,99.0,WAS,88,0,2016,2015-10-28,False
4,240.0,33.0,84.0,0.393,7.0,28.0,0.250,15.0,25.0,0.600,...,30.8,25.2,134.0,98.0,ORL,87,1,2016,2015-10-28,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17529,240.0,38.0,82.0,0.463,17.0,46.0,0.370,13.0,14.0,0.929,...,50.0,40.0,205.0,124.0,DAL,99,1,2024,2024-06-12,True
17530,240.0,46.0,91.0,0.505,15.0,37.0,0.405,15.0,22.0,0.682,...,50.0,35.9,200.0,138.0,BOS,84,0,2024,2024-06-14,True
17531,240.0,29.0,80.0,0.363,14.0,41.0,0.341,12.0,13.0,0.923,...,100.0,40.8,212.0,99.0,DAL,122,1,2024,2024-06-14,False
17532,240.0,38.0,89.0,0.427,13.0,39.0,0.333,17.0,20.0,0.850,...,36.4,54.6,194.0,133.0,DAL,88,0,2024,2024-06-17,True
17533,240.0,35.0,78.0,0.449,11.0,37.0,0.297,7.0,13.0,0.538,...,15.5,32.3,300.0,110.0,BOS,106,1,2024,2024-06-17,False

In [9]:
def add_target(Team):
    Team["target"] = Team["won"].shift(-1)
    return Team

df = df.groupby("Team", group_keys=False).apply(add_target)

/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Team["target"] = Team["won"].shift(-1)
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2909186604.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby("Team", group_keys=False).apply(add_target)

In [10]:
df[df["Team"] == "WAS"]

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,Team_opp,Total_opp,Home_opp,season,date,won,target
4,240.0,33.0,84.0,0.393,7.0,28.0,0.250,15.0,25.0,0.600,...,25.2,134.0,98.0,ORL,87,1,2016,2015-10-28,True,True
41,240.0,35.0,68.0,0.515,12.0,21.0,0.571,36.0,44.0,0.818,...,32.4,138.0,122.0,MIL,113,1,2016,2015-10-30,True,False
51,240.0,38.0,90.0,0.422,6.0,22.0,0.273,28.0,33.0,0.848,...,28.7,153.0,108.0,NYK,117,0,2016,2015-10-31,False,True
88,240.0,42.0,87.0,0.483,8.0,23.0,0.348,10.0,14.0,0.714,...,30.0,160.0,109.0,SAS,99,0,2016,2015-11-04,True,False
136,240.0,38.0,78.0,0.487,8.0,24.0,0.333,15.0,17.0,0.882,...,31.4,155.0,108.0,ATL,114,1,2016,2015-11-07,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17271,240.0,38.0,88.0,0.432,5.0,33.0,0.152,21.0,30.0,0.700,...,31.5,144.0,114.0,POR,108,0,2024,2024-04-05,False,False
17295,240.0,42.0,89.0,0.472,16.0,40.0,0.400,22.0,30.0,0.733,...,30.4,145.0,120.0,TOR,130,1,2024,2024-04-07,False,False
17309,240.0,44.0,89.0,0.494,20.0,43.0,0.465,13.0,17.0,0.765,...,72.4,199.0,131.0,MIN,130,1,2024,2024-04-09,False,False
17361,240.0,45.0,86.0,0.523,18.0,43.0,0.419,19.0,29.0,0.655,...,29.3,159.0,127.0,CHI,129,0,2024,2024-04-12,False,False
17374,240.0,49.0,103.0,0.476,14.0,38.0,0.368,10.0,10.0,1.000,...,40.2,199.0,128.0,BOS,132,1,2024,2024-04-14,False,NaN

In [11]:
df["target"][pd.isnull(df["target"])] = 2

/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/1618397414.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["target"][pd.isnull(df["target"])] = 2
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/1618397414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2

In [12]:
df["target"] = df["target"].astype(int, errors="ignore")

In [13]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,Team_opp,Total_opp,Home_opp,season,date,won,target
0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
1,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,0.769,...,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True,1
2,240.0,29.0,82.0,0.354,2.0,16.0,0.125,16.0,22.0,0.727,...,28.0,149.0,89.0,CLE,106,0,2016,2015-10-28,False,1
3,240.0,37.0,100.0,0.370,5.0,26.0,0.192,8.0,12.0,0.667,...,29.7,121.0,99.0,WAS,88,0,2016,2015-10-28,False,0
4,240.0,33.0,84.0,0.393,7.0,28.0,0.250,15.0,25.0,0.600,...,25.2,134.0,98.0,ORL,87,1,2016,2015-10-28,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17529,240.0,38.0,82.0,0.463,17.0,46.0,0.370,13.0,14.0,0.929,...,40.0,205.0,124.0,DAL,99,1,2024,2024-06-12,True,0
17530,240.0,46.0,91.0,0.505,15.0,37.0,0.405,15.0,22.0,0.682,...,35.9,200.0,138.0,BOS,84,0,2024,2024-06-14,True,0
17531,240.0,29.0,80.0,0.363,14.0,41.0,0.341,12.0,13.0,0.923,...,40.8,212.0,99.0,DAL,122,1,2024,2024-06-14,False,1
17532,240.0,38.0,89.0,0.427,13.0,39.0,0.333,17.0,20.0,0.850,...,54.6,194.0,133.0,DAL,88,0,2024,2024-06-17,True,2
17533,240.0,35.0,78.0,0.449,11.0,37.0,0.297,7.0,13.0,0.538,...,32.3,300.0,110.0,BOS,106,1,2024,2024-06-17,False,2

In [14]:
df["won"].value_counts()

won
False    8767
True     8767
Name: count, dtype: int64

In [15]:
df["target"].value_counts()

target
1    8752
0    8752
2      30
Name: count, dtype: int64

In [16]:
nulls = pd.isnull(df)

In [18]:
nulls = nulls.sum()

In [21]:
nulls = nulls[nulls > 0]

In [23]:
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [24]:
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'orb',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'Team_opp', 'Total_opp',
       'Home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=138)

In [25]:
df = df[valid_columns].copy()

In [26]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,Team_opp,Total_opp,Home_opp,season,date,won,target
0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,7.0,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
1,240.0,37.0,96.0,0.385,12.0,29.0,0.414,20.0,26.0,23.0,...,33.8,258.0,121.0,ATL,94,1,2016,2015-10-27,True,1
2,240.0,29.0,82.0,0.354,2.0,16.0,0.125,16.0,22.0,11.0,...,28.0,149.0,89.0,CLE,106,0,2016,2015-10-28,False,1
3,240.0,37.0,100.0,0.370,5.0,26.0,0.192,8.0,12.0,17.0,...,29.7,121.0,99.0,WAS,88,0,2016,2015-10-28,False,0
4,240.0,33.0,84.0,0.393,7.0,28.0,0.250,15.0,25.0,15.0,...,25.2,134.0,98.0,ORL,87,1,2016,2015-10-28,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17529,240.0,38.0,82.0,0.463,17.0,46.0,0.370,13.0,14.0,6.0,...,40.0,205.0,124.0,DAL,99,1,2024,2024-06-12,True,0
17530,240.0,46.0,91.0,0.505,15.0,37.0,0.405,15.0,22.0,13.0,...,35.9,200.0,138.0,BOS,84,0,2024,2024-06-14,True,0
17531,240.0,29.0,80.0,0.363,14.0,41.0,0.341,12.0,13.0,4.0,...,40.8,212.0,99.0,DAL,122,1,2024,2024-06-14,False,1
17532,240.0,38.0,89.0,0.427,13.0,39.0,0.333,17.0,20.0,15.0,...,54.6,194.0,133.0,DAL,88,0,2024,2024-06-17,True,2
17533,240.0,35.0,78.0,0.449,11.0,37.0,0.297,7.0,13.0,7.0,...,32.3,300.0,110.0,BOS,106,1,2024,2024-06-17,False,2

In [27]:
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.5.1-cp311-cp311-macosx_12_0_arm64.whl.metadata (12 kB)
Requirement already satisfied: numpy>=1.19.5 in ./miniconda3/lib/python3.11/site-packages (from scikit-learn) (2.0.1)
Collecting scipy>=1.6.0 (from scikit-learn)
  Downloading scipy-1.14.1-cp311-cp311-macosx_14_0_arm64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 2.2 MB/s eta 0:00:00
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.5.1-cp311-cp311-macosx_12_0_arm64.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 18.9 MB/s eta 0:00:00a 0:00:01
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.8/301.8 kB 19.4 MB/s eta 0:00:00
Downloading scipy-1.14.1-cp311-cp311-macosx_14_0_arm64.whl (23.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/23.1 MB 18.5 MB/s eta 0:00:0000:0100:01
Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.5.1 scipy-1.14.1 threadpoolctl-3.5.0
Note: you may need to restart the kernel to use updated packages.

In [29]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)

sfs=SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward",cv=split)

In [38]:
removed_columns = ["season","date","won","target","Team","Team_opp"]

In [39]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [40]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [41]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,Team_opp,Total_opp,Home_opp,season,date,won,target
0,0.0,0.409091,0.323529,0.432692,0.275862,0.348485,0.351544,0.272727,0.234375,0.241379,...,0.019255,0.172414,0.306818,DET,0.446809,0.0,2016,2015-10-27,False,1
1,0.0,0.409091,0.529412,0.274038,0.413793,0.378788,0.491686,0.454545,0.406250,0.793103,...,0.150193,0.793103,0.500000,ATL,0.319149,1.0,2016,2015-10-27,True,1
2,0.0,0.227273,0.323529,0.199519,0.068966,0.181818,0.148456,0.363636,0.343750,0.379310,...,0.075738,0.256158,0.136364,CLE,0.446809,0.0,2016,2015-10-28,False,1
3,0.0,0.409091,0.588235,0.237981,0.172414,0.333333,0.228029,0.181818,0.187500,0.586207,...,0.097561,0.118227,0.250000,WAS,0.255319,0.0,2016,2015-10-28,False,0
4,0.0,0.318182,0.352941,0.293269,0.241379,0.363636,0.296912,0.340909,0.390625,0.517241,...,0.039795,0.182266,0.238636,ORL,0.244681,1.0,2016,2015-10-28,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17529,0.0,0.431818,0.323529,0.461538,0.586207,0.636364,0.439430,0.295455,0.218750,0.206897,...,0.229782,0.532020,0.534091,DAL,0.372340,1.0,2024,2024-06-12,True,0
17530,0.0,0.613636,0.455882,0.562500,0.517241,0.500000,0.480998,0.340909,0.343750,0.448276,...,0.177150,0.507389,0.693182,BOS,0.212766,0.0,2024,2024-06-14,True,0
17531,0.0,0.227273,0.294118,0.221154,0.482759,0.560606,0.404988,0.272727,0.203125,0.137931,...,0.240051,0.566502,0.250000,DAL,0.617021,1.0,2024,2024-06-14,False,1
17532,0.0,0.431818,0.426471,0.375000,0.448276,0.530303,0.395487,0.386364,0.312500,0.517241,...,0.417202,0.477833,0.636364,DAL,0.255319,0.0,2024,2024-06-17,True,2
17533,0.0,0.363636,0.264706,0.427885,0.379310,0.500000,0.352732,0.159091,0.203125,0.241379,...,0.130937,1.000000,0.375000,BOS,0.446809,1.0,2024,2024-06-17,False,2

In [42]:
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [43]:
predictors = list(selected_columns[sfs.get_support()])

In [44]:
predictors

['orb',
 'tov',
 'pts',
 'efg%',
 'tov%',
 'usg%',
 'ortg',
 'drtg',
 'orb_max',
 'tov_max',
 'gmsc_max',
 'drb%_max',
 'Total',
 '3p_opp',
 'fta_opp',
 'drb_opp',
 'blk_opp',
 'pts_opp',
 'ftr_opp',
 'usg%_opp',
 'ortg_opp',
 'drtg_opp',
 '3pa_max_opp',
 'trb_max_opp',
 'ast_max_opp',
 'gmsc_max_opp',
 'efg%_max_opp',
 'ast%_max_opp',
 'tov%_max_opp',
 'Total_opp']

In [48]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []

    seasons = sorted(data["season"].unique())

    for i in range(start, len(seasons), step):
        season = seasons[i]

        train = data[data["season"] < season]
        test = data[data["season"] == season]

        model.fit(train[predictors], train["target"])

        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)

        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actual", "predictions"]

        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [49]:
predictions = backtest(df,rr,predictors)

In [50]:
predictions

       actual  predictions
4054        1            0
4055        1            1
4056        1            0
4057        1            0
4058        1            0
...       ...          ...
17529       0            1
17530       0            1
17531       1            0
17532       2            1
17533       2            1

[13480 rows x 2 columns]

In [51]:
from sklearn.metrics import accuracy_score

predictions = predictions[predictions["actual"] != 2]
accuracy_score(predictions["actual"], predictions["predictions"])

0.5481040892193308

In [66]:
df.groupby("Home").apply(lambda x: x[x["won"] == 1].shape[0]/x.shape[0])

/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/2787503949.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("Home").apply(lambda x: x[x["won"] == 1].shape[0]/x.shape[0])

Home
0.0    0.425345
1.0    0.574655
dtype: float64

In [54]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,Team_opp,Total_opp,Home_opp,season,date,won,target
0,0.0,0.409091,0.323529,0.432692,0.275862,0.348485,0.351544,0.272727,0.234375,0.241379,...,0.019255,0.172414,0.306818,DET,0.446809,0.0,2016,2015-10-27,False,1
1,0.0,0.409091,0.529412,0.274038,0.413793,0.378788,0.491686,0.454545,0.406250,0.793103,...,0.150193,0.793103,0.500000,ATL,0.319149,1.0,2016,2015-10-27,True,1
2,0.0,0.227273,0.323529,0.199519,0.068966,0.181818,0.148456,0.363636,0.343750,0.379310,...,0.075738,0.256158,0.136364,CLE,0.446809,0.0,2016,2015-10-28,False,1
3,0.0,0.409091,0.588235,0.237981,0.172414,0.333333,0.228029,0.181818,0.187500,0.586207,...,0.097561,0.118227,0.250000,WAS,0.255319,0.0,2016,2015-10-28,False,0
4,0.0,0.318182,0.352941,0.293269,0.241379,0.363636,0.296912,0.340909,0.390625,0.517241,...,0.039795,0.182266,0.238636,ORL,0.244681,1.0,2016,2015-10-28,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17529,0.0,0.431818,0.323529,0.461538,0.586207,0.636364,0.439430,0.295455,0.218750,0.206897,...,0.229782,0.532020,0.534091,DAL,0.372340,1.0,2024,2024-06-12,True,0
17530,0.0,0.613636,0.455882,0.562500,0.517241,0.500000,0.480998,0.340909,0.343750,0.448276,...,0.177150,0.507389,0.693182,BOS,0.212766,0.0,2024,2024-06-14,True,0
17531,0.0,0.227273,0.294118,0.221154,0.482759,0.560606,0.404988,0.272727,0.203125,0.137931,...,0.240051,0.566502,0.250000,DAL,0.617021,1.0,2024,2024-06-14,False,1
17532,0.0,0.431818,0.426471,0.375000,0.448276,0.530303,0.395487,0.386364,0.312500,0.517241,...,0.417202,0.477833,0.636364,DAL,0.255319,0.0,2024,2024-06-17,True,2
17533,0.0,0.363636,0.264706,0.427885,0.379310,0.500000,0.352732,0.159091,0.203125,0.241379,...,0.130937,1.000000,0.375000,BOS,0.446809,1.0,2024,2024-06-17,False,2

In [72]:
df_rolling = df[list(selected_columns) + ["won", "Team", "season"]]

In [73]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,Total_opp,Home_opp,won,Team,season
0,0.0,0.409091,0.323529,0.432692,0.275862,0.348485,0.351544,0.272727,0.234375,0.241379,...,0.047,0.300839,0.019255,0.172414,0.306818,0.446809,0.0,False,ATL,2016
1,0.0,0.409091,0.529412,0.274038,0.413793,0.378788,0.491686,0.454545,0.406250,0.793103,...,0.071,0.550314,0.150193,0.793103,0.500000,0.319149,1.0,True,DET,2016
2,0.0,0.227273,0.323529,0.199519,0.068966,0.181818,0.148456,0.363636,0.343750,0.379310,...,0.122,1.000000,0.075738,0.256158,0.136364,0.446809,0.0,False,MEM,2016
3,0.0,0.409091,0.588235,0.237981,0.172414,0.333333,0.228029,0.181818,0.187500,0.586207,...,0.082,0.196017,0.097561,0.118227,0.250000,0.255319,0.0,False,ORL,2016
4,0.0,0.318182,0.352941,0.293269,0.241379,0.363636,0.296912,0.340909,0.390625,0.517241,...,0.116,0.274633,0.039795,0.182266,0.238636,0.244681,1.0,True,WAS,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17529,0.0,0.431818,0.323529,0.461538,0.586207,0.636364,0.439430,0.295455,0.218750,0.206897,...,0.082,0.475891,0.229782,0.532020,0.534091,0.372340,1.0,True,BOS,2024
17530,0.0,0.613636,0.455882,0.562500,0.517241,0.500000,0.480998,0.340909,0.343750,0.448276,...,0.164,0.475891,0.177150,0.507389,0.693182,0.212766,0.0,True,DAL,2024
17531,0.0,0.227273,0.294118,0.221154,0.482759,0.560606,0.404988,0.272727,0.203125,0.137931,...,0.125,1.000000,0.240051,0.566502,0.250000,0.617021,1.0,False,BOS,2024
17532,0.0,0.431818,0.426471,0.375000,0.448276,0.530303,0.395487,0.386364,0.312500,0.517241,...,0.056,0.333333,0.417202,0.477833,0.636364,0.255319,0.0,True,BOS,2024
17533,0.0,0.363636,0.264706,0.427885,0.379310,0.500000,0.352732,0.159091,0.203125,0.241379,...,0.031,0.114256,0.130937,1.000000,0.375000,0.446809,1.0,False,DAL,2024

In [75]:
def find_team_averages(Team):
    Team = Team.select_dtypes(include=[float, int])
    rolling = Team.rolling(10).mean()
    return rolling

df_rolling = df_rolling.groupby(["Team","season"], group_keys=False).apply(find_team_averages)

/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/663774192.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_rolling = df_rolling.groupby(["Team","season"], group_keys=False).apply(find_team_averages)

In [76]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,Total_opp,Home_opp,season
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17529,0.025,0.488636,0.350000,0.511298,0.510345,0.560606,0.427672,0.379545,0.328125,0.331034,...,0.394610,0.0416,0.1001,0.491405,0.173171,0.462069,0.570455,0.426596,0.4,2024.0
17530,0.000,0.472727,0.333824,0.510096,0.420690,0.424242,0.447625,0.356818,0.326562,0.351724,...,0.273280,0.0554,0.0965,0.270021,0.253530,0.429064,0.544318,0.409574,0.4,2024.0
17531,0.025,0.459091,0.354412,0.467548,0.503448,0.562121,0.420665,0.365909,0.306250,0.317241,...,0.396101,0.0433,0.1126,0.570021,0.173042,0.510837,0.534091,0.467021,0.5,2024.0
17532,0.025,0.470455,0.367647,0.470913,0.520690,0.568182,0.433017,0.359091,0.300000,0.348276,...,0.405390,0.0438,0.1079,0.576310,0.194865,0.533005,0.560227,0.435106,0.5,2024.0
17533,0.000,0.470455,0.319118,0.519712,0.417241,0.427273,0.442162,0.345455,0.310937,0.334483,...,0.278211,0.0539,0.0905,0.251363,0.249294,0.497044,0.539773,0.415957,0.5,2024.0

In [77]:
rolling_cols = [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols

df = pd.concat([df,df_rolling], axis=1)

In [78]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,ast%_max_opp_10,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,Total_opp_10,Home_opp_10,season_10
0,0.0,0.409091,0.323529,0.432692,0.275862,0.348485,0.351544,0.272727,0.234375,0.241379,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.409091,0.529412,0.274038,0.413793,0.378788,0.491686,0.454545,0.406250,0.793103,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.227273,0.323529,0.199519,0.068966,0.181818,0.148456,0.363636,0.343750,0.379310,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.409091,0.588235,0.237981,0.172414,0.333333,0.228029,0.181818,0.187500,0.586207,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.318182,0.352941,0.293269,0.241379,0.363636,0.296912,0.340909,0.390625,0.517241,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17529,0.0,0.431818,0.323529,0.461538,0.586207,0.636364,0.439430,0.295455,0.218750,0.206897,...,0.394610,0.0416,0.1001,0.491405,0.173171,0.462069,0.570455,0.426596,0.4,2024.0
17530,0.0,0.613636,0.455882,0.562500,0.517241,0.500000,0.480998,0.340909,0.343750,0.448276,...,0.273280,0.0554,0.0965,0.270021,0.253530,0.429064,0.544318,0.409574,0.4,2024.0
17531,0.0,0.227273,0.294118,0.221154,0.482759,0.560606,0.404988,0.272727,0.203125,0.137931,...,0.396101,0.0433,0.1126,0.570021,0.173042,0.510837,0.534091,0.467021,0.5,2024.0
17532,0.0,0.431818,0.426471,0.375000,0.448276,0.530303,0.395487,0.386364,0.312500,0.517241,...,0.405390,0.0438,0.1079,0.576310,0.194865,0.533005,0.560227,0.435106,0.5,2024.0
17533,0.0,0.363636,0.264706,0.427885,0.379310,0.500000,0.352732,0.159091,0.203125,0.241379,...,0.278211,0.0539,0.0905,0.251363,0.249294,0.497044,0.539773,0.415957,0.5,2024.0

In [79]:
df = df.dropna()

In [80]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,ast%_max_opp_10,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,Total_opp_10,Home_opp_10,season_10
190,0.0,0.318182,0.132353,0.497596,0.275862,0.272727,0.432304,0.590909,0.453125,0.344828,...,0.307569,0.0741,0.0982,0.313312,0.179974,0.480296,0.455682,0.421277,0.5,2016.0
210,0.0,0.431818,0.397059,0.399038,0.137931,0.212121,0.263658,0.431818,0.375000,0.206897,...,0.380161,0.0747,0.0697,0.311111,0.127086,0.389163,0.387500,0.403191,0.5,2016.0
223,0.0,0.204545,0.250000,0.223558,0.206897,0.318182,0.285036,0.522727,0.453125,0.344828,...,0.305505,0.0785,0.0820,0.351258,0.109628,0.315764,0.465909,0.426596,0.4,2016.0
226,0.0,0.363636,0.426471,0.293269,0.172414,0.257576,0.282660,0.431818,0.328125,0.551724,...,0.298853,0.0764,0.1006,0.316771,0.177407,0.475369,0.452273,0.434043,0.6,2016.0
229,0.0,0.272727,0.220588,0.341346,0.241379,0.227273,0.437055,0.250000,0.203125,0.137931,...,0.332913,0.0730,0.0805,0.304088,0.172657,0.474877,0.453409,0.415957,0.6,2016.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17529,0.0,0.431818,0.323529,0.461538,0.586207,0.636364,0.439430,0.295455,0.218750,0.206897,...,0.394610,0.0416,0.1001,0.491405,0.173171,0.462069,0.570455,0.426596,0.4,2024.0
17530,0.0,0.613636,0.455882,0.562500,0.517241,0.500000,0.480998,0.340909,0.343750,0.448276,...,0.273280,0.0554,0.0965,0.270021,0.253530,0.429064,0.544318,0.409574,0.4,2024.0
17531,0.0,0.227273,0.294118,0.221154,0.482759,0.560606,0.404988,0.272727,0.203125,0.137931,...,0.396101,0.0433,0.1126,0.570021,0.173042,0.510837,0.534091,0.467021,0.5,2024.0
17532,0.0,0.431818,0.426471,0.375000,0.448276,0.530303,0.395487,0.386364,0.312500,0.517241,...,0.405390,0.0438,0.1079,0.576310,0.194865,0.533005,0.560227,0.435106,0.5,2024.0
17533,0.0,0.363636,0.264706,0.427885,0.379310,0.500000,0.352732,0.159091,0.203125,0.241379,...,0.278211,0.0539,0.0905,0.251363,0.249294,0.497044,0.539773,0.415957,0.5,2024.0

In [83]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col

def add_col(df, col_name):
    return df.groupby("Team", group_keys=False).apply(lambda x: shift_col(x, col_name))

df["home_next"] = add_col(df, "Home")
df["Team_opp_next"] = add_col(df, "Team_opp")
df["date_next"] = add_col(df, "date")

/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/3916390650.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("Team", group_keys=False).apply(lambda x: shift_col(x, col_name))
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/3916390650.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["home_next"] = add_col(df, "Home")
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/3916390650.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("Team", group_keys=False).apply(lambda x: shift_col(x, col_name))
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/3916390650.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Team_opp_next"] = add_col(df, "Team_opp")
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/3916390650.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("Team", group_keys=False).apply(lambda x: shift_col(x, col_name))
/var/folders/fw/30s_y21x6rs1d8k76h6kkf_m0000gn/T/ipykernel_49195/3916390650.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_next"] = add_col(df, "date")

In [84]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,Total_opp_10,Home_opp_10,season_10,home_next,Team_opp_next,date_next
190,0.0,0.318182,0.132353,0.497596,0.275862,0.272727,0.432304,0.590909,0.453125,0.344828,...,0.313312,0.179974,0.480296,0.455682,0.421277,0.5,2016.0,0.0,CHO,2015-11-15
210,0.0,0.431818,0.397059,0.399038,0.137931,0.212121,0.263658,0.431818,0.375000,0.206897,...,0.311111,0.127086,0.389163,0.387500,0.403191,0.5,2016.0,1.0,MIN,2015-11-18
223,0.0,0.204545,0.250000,0.223558,0.206897,0.318182,0.285036,0.522727,0.453125,0.344828,...,0.351258,0.109628,0.315764,0.465909,0.426596,0.4,2016.0,0.0,MEM,2015-11-16
226,0.0,0.363636,0.426471,0.293269,0.172414,0.257576,0.282660,0.431818,0.328125,0.551724,...,0.316771,0.177407,0.475369,0.452273,0.434043,0.6,2016.0,0.0,SAS,2015-11-16
229,0.0,0.272727,0.220588,0.341346,0.241379,0.227273,0.437055,0.250000,0.203125,0.137931,...,0.304088,0.172657,0.474877,0.453409,0.415957,0.6,2016.0,0.0,HOU,2015-11-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17529,0.0,0.431818,0.323529,0.461538,0.586207,0.636364,0.439430,0.295455,0.218750,0.206897,...,0.491405,0.173171,0.462069,0.570455,0.426596,0.4,2024.0,0.0,DAL,2024-06-14
17530,0.0,0.613636,0.455882,0.562500,0.517241,0.500000,0.480998,0.340909,0.343750,0.448276,...,0.270021,0.253530,0.429064,0.544318,0.409574,0.4,2024.0,0.0,BOS,2024-06-17
17531,0.0,0.227273,0.294118,0.221154,0.482759,0.560606,0.404988,0.272727,0.203125,0.137931,...,0.570021,0.173042,0.510837,0.534091,0.467021,0.5,2024.0,1.0,DAL,2024-06-17
17532,0.0,0.431818,0.426471,0.375000,0.448276,0.530303,0.395487,0.386364,0.312500,0.517241,...,0.576310,0.194865,0.533005,0.560227,0.435106,0.5,2024.0,NaN,None,None
17533,0.0,0.363636,0.264706,0.427885,0.379310,0.500000,0.352732,0.159091,0.203125,0.241379,...,0.251363,0.249294,0.497044,0.539773,0.415957,0.5,2024.0,NaN,None,None

In [85]:
df = df.copy()

In [86]:
full = df.merge(df[rolling_cols + ["Team_opp_next", "date_next", "Team"]], 
                left_on=["Team", "date_next"], 
                right_on=["Team_opp_next", "date_next"]
               )

In [87]:
full

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,blk%_max_opp_10_y,tov%_max_opp_10_y,usg%_max_opp_10_y,ortg_max_opp_10_y,drtg_max_opp_10_y,Total_opp_10_y,Home_opp_10_y,season_10_y,Team_opp_next_y,Team_y
0,0.00,0.409091,0.352941,0.406250,0.413793,0.196970,0.838480,0.818182,0.609375,0.413793,...,0.0996,0.568973,0.125802,0.332512,0.407955,0.467021,0.4,2016.0,MEM,HOU
1,0.00,0.522727,0.382353,0.521635,0.310345,0.212121,0.593824,0.363636,0.312500,0.344828,...,0.0742,0.384172,0.155712,0.452709,0.407955,0.494681,0.6,2016.0,SAS,NOP
2,0.25,0.363636,0.411765,0.305288,0.310345,0.393939,0.356295,0.545455,0.453125,0.344828,...,0.0690,0.389308,0.198716,0.309360,0.438636,0.434043,0.3,2016.0,POR,LAC
3,0.25,0.500000,0.735294,0.245192,0.310345,0.257576,0.509501,0.295455,0.328125,0.689655,...,0.0916,0.425367,0.143132,0.348768,0.405682,0.455319,0.3,2016.0,ORL,SAC
4,0.25,0.295455,0.470588,0.185096,0.482759,0.606061,0.377672,0.681818,0.546875,0.448276,...,0.0880,0.390881,0.140822,0.491133,0.394318,0.420213,0.7,2016.0,HOU,MEM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14813,0.00,0.454545,0.323529,0.492788,0.551724,0.575758,0.452494,0.295455,0.296875,0.344828,...,0.0809,0.209224,0.250449,0.413300,0.544318,0.431915,0.5,2024.0,BOS,DAL
14814,0.00,0.431818,0.382353,0.411058,0.310345,0.318182,0.427553,0.318182,0.250000,0.241379,...,0.1001,0.491405,0.173171,0.462069,0.570455,0.426596,0.4,2024.0,DAL,BOS
14815,0.00,0.431818,0.323529,0.461538,0.586207,0.636364,0.439430,0.295455,0.218750,0.206897,...,0.0900,0.237421,0.253915,0.403941,0.523864,0.427660,0.4,2024.0,BOS,DAL
14816,0.00,0.613636,0.455882,0.562500,0.517241,0.500000,0.480998,0.340909,0.343750,0.448276,...,0.1126,0.570021,0.173042,0.510837,0.534091,0.467021,0.5,2024.0,DAL,BOS
14817,0.00,0.227273,0.294118,0.221154,0.482759,0.560606,0.404988,0.272727,0.203125,0.137931,...,0.0965,0.270021,0.253530,0.429064,0.544318,0.409574,0.4,2024.0,BOS,DAL

In [88]:
full[["Team_x", "Team_opp_next_x", "Team_y","Team_opp_next_y", "date_next"]]

      Team_x Team_opp_next_x Team_y Team_opp_next_y   date_next
0        MEM             HOU    HOU             MEM  2015-11-20
1        SAS             NOP    NOP             SAS  2015-11-20
2        POR             LAC    LAC             POR  2015-11-20
3        ORL             SAC    SAC             ORL  2015-11-21
4        HOU             MEM    MEM             HOU  2015-11-20
...      ...             ...    ...             ...         ...
14813    BOS             DAL    DAL             BOS  2024-06-12
14814    DAL             BOS    BOS             DAL  2024-06-14
14815    BOS             DAL    DAL             BOS  2024-06-14
14816    DAL             BOS    BOS             DAL  2024-06-17
14817    BOS             DAL    DAL             BOS  2024-06-17

[14818 rows x 5 columns]

In [89]:
removed_columns = list(full.columns[full.dtypes == "object"]) + removed_columns

In [90]:
removed_columns

['Team_x',
 'Team_opp',
 'date',
 'Team_opp_next_x',
 'date_next',
 'Team_opp_next_y',
 'Team_y',
 'season',
 'date',
 'won',
 'target',
 'Team',
 'Team_opp']

In [91]:
selected_columns = full.columns[~full.columns.isin(removed_columns)]

In [92]:
sfs.fit(full[selected_columns], full["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [94]:
predictors = list(selected_columns[sfs.get_support()])

In [95]:
predictors

['fg',
 'ts%',
 'usg%',
 'efg%_max',
 'usg%_opp',
 'fga_10_x',
 'fta_10_x',
 'ts%_10_x',
 'ftr_10_x',
 'usg%_10_x',
 'gmsc_max_10_x',
 'fg%_opp_10_x',
 'ast_opp_10_x',
 'pts_opp_10_x',
 'usg%_opp_10_x',
 'stl_max_opp_10_x',
 'tov_max_opp_10_x',
 'stl%_max_opp_10_x',
 'home_next',
 'fg%_10_y',
 '3p%_10_y',
 'usg%_10_y',
 'ortg_10_y',
 'drtg_10_y',
 '3p%_max_10_y',
 '3p_opp_10_y',
 'drb_opp_10_y',
 'tov%_opp_10_y',
 'usg%_opp_10_y',
 'ortg_opp_10_y']

In [96]:
predictions = backtest(full,rr,predictors)

In [101]:
accuracy_score(predictions["actual"], predictions["predictions"])

0.6331896930788848